"""add uniq

Revision ID: 18e196d2b7e7
Revises: 7124d023e527
Create Date: 2026-09-19 21:44:24.112467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e196d2b7e7'
down_revision: Union[str, Sequence[str], None] = '7124d023e527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'company_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('user_id_company_name', 'companies', ['user_id', 'company_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_company_name', 'companies', type_='unique')
    op.alter_column('companies', 'company_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
